In [1]:
import torch as t

In [2]:
print(t.__version__)

1.5.0+cpu


In [3]:
####################################张量
n1=t.empty(5,3)#未初始化
print(n1)

n2=t.rand(5,3)#随机初始化
print(n2)

n3=t.randn(5,3)#从正态分布中随机取数 
print(n3)
#t.ones, t.zeros分别是全1初始化和全0初始化

tensor([[9.2755e-39, 1.0561e-38, 9.5510e-39],
        [8.9082e-39, 9.4592e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])
tensor([[0.0787, 0.7452, 0.0479],
        [0.5004, 0.4221, 0.3962],
        [0.7225, 0.8788, 0.3133],
        [0.6337, 0.0854, 0.8931],
        [0.2155, 0.4889, 0.0119]])
tensor([[ 0.8154, -1.8312,  0.0043],
        [-0.9063,  1.6402, -0.7820],
        [ 0.0418,  0.7248, -0.3524],
        [-1.1139, -0.6979, -0.7691],
        [-0.7585, -1.7303, -0.2356]])


In [4]:
n4=t.Tensor([5.2,5.0,3])#直接从数据构造张量

n5=t.Tensor([[5,5,3]])   #中括号‘[]’类似于张量的维度标志

n6=t.tensor([[1,2,3],[4,5,6]])#要注意中括号[]
print(n4,n4.size(),n4.type())
print(n5,n5.size(),n5.type())
print(" ")
print(n6)

tensor([5.2000, 5.0000, 3.0000]) torch.Size([3]) torch.FloatTensor
tensor([[5., 5., 3.]]) torch.Size([1, 3]) torch.FloatTensor
 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
#张量元素的访问
z=t.zeros(2,5,3)
print(z)
print(" ")
print("z[0]=",z[0])#访问z的第一个元素
print(" ")
print("z[0,0]=",z[0,0])#访问z的第一个元素的第一行
print(" ")

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
 
z[0]= tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
 
z[0,0]= tensor([0., 0., 0.])
 


In [6]:
####################################张量的运算

##加法
x=t.ones(5,3)
y=t.rand(5,3)
#两种常用形式
print(x+y)
print(t.add(x,y))
#指定输出
m=t.empty(5,3)
print(m)
t.add(x,y,out=m)
print(m)
##原地加法操作（in_place）
y.add_(x)     #任何一个改变张量的操作(in-place)后面都固定一个_ , 这将改变原有的数据    x.copy_(y);x.t_()都将改变x的值
print(y)

print("  ")
#广播机制 适当复制元素使其形状相同然后运算
x = t.arange(1, 3).view(1, 2)
print(x,x.size())
y = t.arange(1, 4).view(3, 1)
print(y,y.size())
print(x + y,(x+y).size())

tensor([[1.6624, 1.7210, 1.2190],
        [1.1160, 1.2184, 1.3170],
        [1.8770, 1.2515, 1.5803],
        [1.3650, 1.5778, 1.4657],
        [1.3006, 1.4302, 1.7274]])
tensor([[1.6624, 1.7210, 1.2190],
        [1.1160, 1.2184, 1.3170],
        [1.8770, 1.2515, 1.5803],
        [1.3650, 1.5778, 1.4657],
        [1.3006, 1.4302, 1.7274]])
tensor([[1.6624, 1.7210, 1.2190],
        [1.1160, 1.2184, 1.3170],
        [1.8770, 1.2515, 1.5803],
        [1.3650, 1.5778, 1.4657],
        [1.3006, 1.4302, 1.7274]])
tensor([[1.6624, 1.7210, 1.2190],
        [1.1160, 1.2184, 1.3170],
        [1.8770, 1.2515, 1.5803],
        [1.3650, 1.5778, 1.4657],
        [1.3006, 1.4302, 1.7274]])
tensor([[1.6624, 1.7210, 1.2190],
        [1.1160, 1.2184, 1.3170],
        [1.8770, 1.2515, 1.5803],
        [1.3650, 1.5778, 1.4657],
        [1.3006, 1.4302, 1.7274]])
  
tensor([[1, 2]]) torch.Size([1, 2])
tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])
tensor([[2, 3],
        [3, 4],
        [4, 5]]

In [7]:
#############################张量的维度操作
#矩阵乘法需要调用mm操作（matrix multiply） Tensor.mm（）
x=t.rand(5,3)
y=t.ones(5,3)
print(x.mm(y.t()))#tensor.t()是矩阵的转置  矩阵乘法需A列=B行，结果取A行B列

tensor([[0.7128, 0.7128, 0.7128, 0.7128, 0.7128],
        [1.8253, 1.8253, 1.8253, 1.8253, 1.8253],
        [0.7076, 0.7076, 0.7076, 0.7076, 0.7076],
        [0.8019, 0.8019, 0.8019, 0.8019, 0.8019],
        [0.8553, 0.8553, 0.8553, 0.8553, 0.8553]])


In [8]:
###############改变形状tensor.view()
#view后的张量与原张量同源 改变一个则都会变化
x=t.ones(4,2)
y=x.view(2,2,2)
print("x=",x,"x.size=",x.size())
print("y=",y,"y.size=",y.size()) 
z=x.view(2,1,-1)       
##################view()操作括号中参数为-1是一种简便操作 , 表示自动计算该维度的元素个数保证重构前后元素个数相同
print(" ")
print("z=",z,"z.size=",z.size())

x= tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) x.size= torch.Size([4, 2])
y= tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]) y.size= torch.Size([2, 2, 2])
 
z= tensor([[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]]) z.size= torch.Size([2, 1, 4])


In [9]:
###########tensor.permute()
#view的操作更像是将张量元素按位置顺序平铺后按规则截取
#permute的操作则是在预原张量维度的基础上进行变换
x=t.tensor([[[1,2,3],[4,5,6]]])
print(x,x.size())
print(x.permute(0,2,1),x.permute(0,2,1).size())

tensor([[[1, 2, 3],
         [4, 5, 6]]]) torch.Size([1, 2, 3])
tensor([[[1, 4],
         [2, 5],
         [3, 6]]]) torch.Size([1, 3, 2])


In [10]:
#########维度的压缩与扩张 tensor.squeese(), tensor.unsqueese()
#指变换某个维度的1
a=t.tensor([[0,1,2],[3,4,5]])
print(a,a.size())
print(" ")
b=a.unsqueeze(1)
print(b,b.size())
print(" ")
c=a.view(1,1,1,2,3)
print(c,c.size())
print(" ")
print(c.squeeze(0),c.squeeze(0).size())


tensor([[0, 1, 2],
        [3, 4, 5]]) torch.Size([2, 3])
 
tensor([[[0, 1, 2]],

        [[3, 4, 5]]]) torch.Size([2, 1, 3])
 
tensor([[[[[0, 1, 2],
           [3, 4, 5]]]]]) torch.Size([1, 1, 1, 2, 3])
 
tensor([[[[0, 1, 2],
          [3, 4, 5]]]]) torch.Size([1, 1, 2, 3])


In [11]:
#########################张量拼接tensor.cat()
#t.cat(seq,dim=0,out=none)
#seq是python序列或相同类型的张量序列
#dim表示沿此维度拼接
#out制定输出
a=t.rand(2,3)
print(a,a.size())
print(" ")
b=t.cat((a,a,a),0)
print(b,b.size())
print(" ")
c=t.cat((a,a,a),1)
print(c,c.size())

tensor([[0.8385, 0.0563, 0.2292],
        [0.8480, 0.8128, 0.3340]]) torch.Size([2, 3])
 
tensor([[0.8385, 0.0563, 0.2292],
        [0.8480, 0.8128, 0.3340],
        [0.8385, 0.0563, 0.2292],
        [0.8480, 0.8128, 0.3340],
        [0.8385, 0.0563, 0.2292],
        [0.8480, 0.8128, 0.3340]]) torch.Size([6, 3])
 
tensor([[0.8385, 0.0563, 0.2292, 0.8385, 0.0563, 0.2292, 0.8385, 0.0563, 0.2292],
        [0.8480, 0.8128, 0.3340, 0.8480, 0.8128, 0.3340, 0.8480, 0.8128, 0.3340]]) torch.Size([2, 9])


In [12]:
#########################张量堆叠t.stack([tensor,tensor],dim)
a=t.tensor([[1,2,3],[4,5,6]])
b=t.tensor([[11,22,33],[44,55,66]])
c=t.stack([a,b],0)
d=t.stack([a,b],1)
e=t.stack([a,b],2)
print(a.size())
print(" ")
print(c,c.size())
print(" ")
print(d,d.size())
print(" ")
print(e,e.size())
print(" ")

torch.Size([2, 3])
 
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 22, 33],
         [44, 55, 66]]]) torch.Size([2, 2, 3])
 
tensor([[[ 1,  2,  3],
         [11, 22, 33]],

        [[ 4,  5,  6],
         [44, 55, 66]]]) torch.Size([2, 2, 3])
 
tensor([[[ 1, 11],
         [ 2, 22],
         [ 3, 33]],

        [[ 4, 44],
         [ 5, 55],
         [ 6, 66]]]) torch.Size([2, 3, 2])
 


In [13]:
###############tensor与numpy数组之间的转换  tensor.numpy(), t.from_numpy()
import numpy as np
a=t.ones(6)
b=a.numpy()
print(a)
print(b)
print(" ")
a=np.ones(6)
b=t.from_numpy(a)
print(a)
print(b)

tensor([1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1.]
 
[1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)
